name: 'actionbuilder_sync'
version: '1.0.0'
config-version: 2
profile: 'actionbuilder_sync'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

seeds:
  actionbuilder_sync:
    1mc_training_map:
      +column_types:
        timeslot_id: INT64
        role_tag: STRING

models:
  actionbuilder_sync:
    +materialized: view
